### PR TITLE
Refactor: Layer Groups + Composer + Labs UI

### PR DESCRIPTION
**Pull request by trbmcginnis**
This branch is a start on integrating labs-layers-api (and labs-ui) into Population Factfinder.

The current plan is to have some layers show up from labs-layers-api while other layers are still local. Labs-layers-api will have to be updated with new layers (census tracts, census blocks, PUMAS) to include them in PopFactfinder. Right now, labs-layers-api layers are showing up as are the local ones with a console error on the "style" of census-tracts-fill. The next steps were to add a lookup-layer-group component in order to add a legend to the "Advanced Options" dropdown, as well as making sure census blocks, tracts, NTAs, and PUMAs show up for the different geometry buttons.

### CODE REVIEW

**Comment by allthesignals** [comment]
@andycochran 
screen shot 2018-12-13 at 12 39 35 pm
^ this button seems to both clear selection and generate report at the same time

**Comment by allthesignals** [comment]
WE shoould keep an eye on our tests:

screen shot 2018-12-13 at 12 42 33 pm

**Comment by andycochran** [comment]
I've fixed the conflicts. I think this PR is ready to merge (unless @allthesignals thinks we need more test coverage).

**Comment by allthesignals** [comment]
@andycochran Test coverage to come!

**Pull request merged**
