### PR TITLE
567 CSV download

### LINKED ISSUE #567: Fix CSV download column order, row order, remove old years, conditional columns, rename variables
we should use the previous columns instead of find the row through nesting - it is only used in one place

### PR DESCRIPTION
**Pull request by trbmcginnis**
This PR updates the CSV download:

**- For ACS profiles**
-removes 2006-2010 rows
-displays reliability and significant columns as TRUE/FALSE
-reorders and removes columns based on attached file in issue #567 
-`change` and `difference` columns changed to `reliable` rather than `significant`

**- For Census**
-removes 2000 rows
-reorders and removes columns based on attached file in issue #567 

Closes #567

### CODE REVIEW

**Comment by allthesignals** [comment]
What's going on with that test?

**Comment by trbmcginnis** [comment]
I think it might be a timeout issue, because when I test it manually it works, and sometimes the tests pass on `ember test` and sometimes they don't. I've seen it take a second to switch from, for example, 4 ntas to 69 census tracts when I click on `data-test-toggle-tracts` so I may edit the test to account for that

**Comment by allthesignals** [comment]
Gotcha - was it doing this before you started this branch?

**Comment by allthesignals** [comment]
@EricaMaurer this was closed and merged, but could you verify that this is in working order? See a preview of the CSV download changes here: https://deploy-preview-686--labs-factfinder.netlify.com.

**Comment by EricaMaurer** [comment]
@allthesignals this still needs to be worked on. Happy to meet on this if helpful.

**Comment by allthesignals** [comment]
@EricaMaurer sure - can you please enumerate the issues about this? I can set up a time for you and @trbmcginnis to meet on this to go over other issues.

**Comment by EricaMaurer** [comment]
Please follow the attached document in issue #567 for appropriate columns to be included in the downloads-- the preview downloads include different columns than the document. All data for the previous timepoints should be included in columns as noted (and removed from rows). We talked about renaming the change and difference significant columns to reliable.

**Comment by trbmcginnis** [comment]
@EricaMaurer 
- Data from 2006-2010 and 2000 were removed in pull request #686 ,
- In pull request #686,  `change_significant`, `change_percent_significant`, and `change_percentage_point_significant` were changed to `change_reliable`, `change_percent_reliable`, and `change_percentage_point_reliable`. I do not see any difference columns that have `significant` in the title. If you are referring to another column, please let me know. 
- In pull request #686, columns were rearranged to match the order specified in the attached document
- PR #691 refactors the code used to delete/add columns to CSV download. Instead of "deleting" the column from memory, we instead are now adding these properties using `push`. Although in the initial `delete` method, downloading the first CSV produced the correct file, there was a bug when the user tried to download a second CSV after switching the mode-->this new method avoids persisting deleted columns, which was causing new CSV downloads to be missing columns when user toggled the `mode`. 
- In PR #691, I included screenshots of each of the four conditions when downloading the CSV's. Let me know if you see any issues with these screenshots.

**Pull request merged**
